#+ endpoint: http://fbwsvcdev.fh-brandenburg.de:8080/fuseki/EduGraph
#+ summary: test2
#+ tags: 
#+   - edugraph

PREFIX schema: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bise:  <http://akwi.de/ns/bise#>
PREFIX dbpedia-de: <http://de.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT DISTINCT * WHERE {
	?universityURI a schema:CollegeOrUniversity;
		schema:url ?universityHomepage;
		schema:location ?universityLocationURI;
		schema:geo ?universityGeoCoordinates.
		
	?universityGeoCoordinates schema:latitude ?universityLatitude;
		schema:longitude ?universityLongitude.
	
	?degreeProgramURI a bise:BISEBachelor;
		schema:provider ?universityURI;
		bise:bisePillar ?degreeProgramPillars;
		bise:cpECTS ?degreeProgramCreditPoints;
		bise:stPeriodOfStudy ?degreeProgramPeriodOfStudy;
		schema:name ?degreeProgramLabel;
		schema:url ?degreeProgramHomepage.
		
	?degreeProgramPillars bise:pillarBAM ?degreeProgramBAMPillar;
		bise:pillarBIS ?degreeProgramBISPillar;
		bise:pillarCSC ?degreeProgramCSCPillar.
		
	?universityLocationURI schema:name ?universityLocationLabel_lang.
	
	FILTER (langMatches(lang(?universityLabel_lang),"de"))
	BIND (str(?universityLabel_lang) AS ?universityLabel)
	
	FILTER (langMatches(lang(?universityLocationLabel_lang),"de"))
	BIND (str(?universityLocationLabel_lang) AS ?universityLocationLabel)	

	
}
